# Generated by Django 5.2.17 on 2026-09-29 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntrepriseApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(auto_created=True, max_length=20, unique=True)),
                ('ville_depart', models.CharField(max_length=100)),
                ('ville_arrivee', models.CharField(max_length=100)),
                ('poids_kg', models.FloatField()),
                ('date_souhaitee', models.DateTimeField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('p', 'publiee'), ('a', 'attribuee'), ('ec', 'en_cours'), ('l', 'livree'), ('an', 'annulee')], default='publiee', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expeditions', to='EntrepriseApp.enterprise')),
            ],
        ),
    ]
