# Generated by Django 5.2.17 on 2026-10-06 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpidationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='poids_kg',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1, 'Le poids ne peut pas etre negative')]),
        ),
    ]
