# Generated by Django 5.2.17 on 2026-09-29 15:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehiculesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicules',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicules',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicules',
            name='type_vehicule',
            field=models.CharField(choices=[('camion', 'Camion'), ('remorque', 'Remorque'), ('fourgon', 'Fourgon')], default='camion', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicules',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
