# Generated by Django 5.2.17 on 2026-09-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehiculesApp', '0002_vehicules_created_at_vehicules_disponible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicules',
            name='type_vehicule',
            field=models.CharField(choices=[], max_length=20),
        ),
    ]
