# Generated by Django 5.2.17 on 2026-10-06 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehiculesApp', '0003_alter_vehicules_type_vehicule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicules',
            name='capacite_kg',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'La capacite ne peut pas etre negative')]),
        ),
    ]
