# Generated by Django 5.2.17 on 2026-09-29 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntrepriseApp', '0001_initial'),
        ('ExpidationApp', '0001_initial'),
        ('VehiculesApp', '0002_vehicules_created_at_vehicules_disponible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.FloatField()),
                ('delais_jour', models.IntegerField()),
                ('status', models.CharField(choices=[('p', 'proposee'), ('a', 'acceptee'), ('r', 'refusee'), ('re', 'retiree')], default='p', max_length=20)),
                ('date_proposition', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='ExpidationApp.expedition')),
                ('transporteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='EntrepriseApp.enterprise')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='VehiculesApp.vehicules')),
            ],
        ),
    ]
