# Generated by Django 5.2.17 on 2026-10-06 15:18

import EntrepriseApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntrepriseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='adress',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20, "L'adresse ne peut pas avoir mois de 20 char"), django.core.validators.MaxLengthValidator(400, "L'adresse ne peut pas avoir plus de 400 char")]),
        ),
        migrations.AlterField(
            model_name='utilisatuer',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[EntrepriseApp.models.validate_email]),
        ),
    ]
